version: 0.1

phases:
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mkdir -p upload_folder
      - export GIT_SHA=`git rev-parse --short HEAD` && echo $GIT_SHA && tar -cvf upload_folder/immigrationhub-ui-$GIT_SHA.tar .
artifacts:
  files:
    - upload_folder/*
  discard-paths: yes
