version: 0.1

environment_variables:
  plaintext:
    BUILD_ENV: "dev"

phases:
  build:
    commands:
      - npm install @angular/cli@1.4.9 && npm install @angular/animations@4.4.6 @angular/common@4.4.6 @angular/compiler@4.4.6 @angular/compiler-cli@4.4.6 @angular/core@4.4.6 @angular/forms@4.4.6 @angular/http@4.4.6 @angular/platform-browser@4.4.6 @angular/platform-browser-dynamic@4.4.6 @angular/platform-server@4.4.6 @angular/router@4.4.6 typescript@2.6.1 && npm i && ng -v && node --max_old_space_size=2048 ./node_modules/@angular/cli/bin/ng build --prod --aot --env=$BUILD_ENV
  post_build:
    commands:
      - mkdir -p upload_folder
      - export GIT_SHA=`git rev-parse --short HEAD` && echo $GIT_SHA && tar -cvf upload_folder/immigrationhub-ui-$GIT_SHA-$BUILD_ENV.tar .
artifacts:
  files:
    - upload_folder/*
  discard-paths: yes
